### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by LastManStandingV2** [cloudposse/terraform-aws-key-pair#34]
```
 Getting source "git::https://github.com/cloudposse/terraform-aws-key-pair.git?ref=master"
Error downloading modules: Error loading modules: module ssh_key_pair: Error parsing .terraform/modules/dd391732868cc6224bc782f7858abb22/main.tf: At 3:16: Unknown token: 3:16 IDENT var.namespace
```

I'm seeing this since the update. I'm using Terraform 0.11.13

**Comment by aknysh** [comment]
@LastManStandingV2 
We converted the module to TF 0.12 and the master branch is on 0.12 now and it will not work with 0.11.
For stability, you should not pin to master because it always changes, pin to a release.
And the last release for 0.11 was 0.3.2.

```
git::https://github.com/cloudposse/terraform-aws-key-pair.git?ref=tags/0.3.2
```

Also don't pin all other modules to master, find the latest release (for 0.11 if you are using TF 0.11) and pin to it.
